import task1 from "../../assets/task1.png";
import task4 from "../../assets/task4.png";
import task6 from "../../assets/task6.png";
import task11 from "../../assets/task11.png";
import { FaRegCheckCircle } from "react-icons/fa";
import avatar1 from "../../assets/task_man1.png";
import avatar2 from "../../assets/task_man2.png";
import avatar3 from "../../assets/task_man3.png";

export const datas = [
  {
    category: "Design",
    image: task1,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    // image: task1,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task4,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task1,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task6,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task1,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task1,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task11,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task1,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task1,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
  {
    category: "Design",
    image: task1,
    title: "Create styleguide foundation",
    text: "create content for peceland App",
    dealLine: "Aug 20, 2024",
    checkIcon: <FaRegCheckCircle />,
    quantity: "0/8",
    avatar1: avatar1,
    avatar2: avatar2,
    avatar3: avatar3,
  },
];
